version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "5000:80"
    volumes:
      - ./backend:/app
    working_dir: /app
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    working_dir: /app
    depends_on:
      - backend
